name: Run linter and tests on pull requests

on:
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.9"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox pip setuptools
      - name: Run formatters
        run: nox -vs format
